# This file was autogenerated by the BETA 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/from-1.5/variables#type-constraints for more info.
# "timestamp" template function replacement
locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/from-1.5/blocks/source
source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "NA"
    task = "Packer Image Creation"
  }
  client_id                         = "f047e53e-843d-4855-9ffd-a0cf3468143b"
  client_secret                     = "kbWA_Pbd5Nvd1e0~1r4WU3-1QsJsNDL7fN"
  image_offer                       = "UbuntuServer"
  image_publisher                   = "Canonical"
  image_sku                         = "18.04-LTS"
  location                          = "UK South"
  managed_image_name                = "MB_dec20"
  managed_image_resource_group_name = "mb-rg"
  os_type                           = "Linux"
  ssh_username                      = "ubuntu"
  subscription_id                   = "8a4a71de-47c9-4d83-86d8-57a0e67ed471"
  tenant_id                         = "8f8fe412-6556-4747-b17e-5f7e14a87a70"
  vm_size                           = "Standard_B1ls"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/from-1.5/blocks/build
build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    script = "scripts/ansible.sh"
  }
  provisioner "ansible-local" {
    group_vars    = "../ansible/group_vars"
    playbook_file = "../ansible/site.yml"
    role_paths    = ["../ansible/roles/git", "../ansible/roles/nginx", "../ansible/roles/growlerfriday"]
  }
  provisioner "shell" {
    script = "scripts/cleanup.sh"
  }
  provisioner "shell" {
    inline = ["echo '************ DEPROVISION'", "sudo /usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"]
  }

  post-processor "manifest" {
    output     = "manifest.json"
    strip_path = true
  }
}
